### ISSUE TITLE
Replace "bespoke" word with something else

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/writing-gradle-tasks#3]
I did not know the word "bespoke". From what I learned it's more common in British English (Google and Wikipedia says so). We have a rule to [write in US English](https://github.com/gradle-guides/style-guide#write-in-us-english) so let's replace it with something else.

> This guide will walk you through the process of customising your build using small, **bespoke** tasks.

**Comment by ysb33r** [comment]
Will use `tailored` instead.
