### ISSUE TITLE
no inputs, no outputs?

### ISSUE THREAD

**Issue by carlolf** [gradle-guides/writing-gradle-tasks#4]
While this small example shows how easy it is to define and execute a Gradle task, it misses what is crucial if a task is part of a build system: input and output definitions. To support "uptodate"...

So, I also think: do not make your examples to easy. In the end, this could lead to deceptions.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #226](https://github.com/gradle/guides/issues/226) via [**ZenHub**](https://www.zenhub.com/)
