### ISSUE TITLE
Broken URL links on writing-gradle-tasks page

### ISSUE THREAD

**Issue by mariauyeda** [gradle-guides/writing-gradle-tasks#9]
All URLs under DOCS heading at the bottom of page go to a 404 page.
<img width="164" alt="screen shot 2018-09-04 at 10 26 16 pm" src="https://user-images.githubusercontent.com/17520506/45073100-a84afa80-b092-11e8-891e-509859ca933a.png">

![image](https://user-images.githubusercontent.com/17520506/45073022-4ee2cb80-b092-11e8-84db-b7e8fd4dc768.png)

**Comment by lacasseio** [comment]
This seems to be fixed, closing.
